<a href="https://colab.research.google.com/github/imtiazdeepto/MLProject/blob/main/Project_2_Heart_disease_prediction/EDA_cardiac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
import os

warnings.filterwarnings('ignore')

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 11

print("✅ Libraries loaded")

✅ Libraries loaded

In [14]:
# import kagglehub

# # Download dataset
# path = kagglehub.dataset_download("redwankarimsony/heart-disease-data")
# print("Path:", path)

# # Find CSV file
# csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
# csv_path = os.path.join(path, csv_files[0])

# # Load
# df = pd.read_csv(csv_path)

# print(f"\n📊 Shape: {df.shape}")
# print(f"\nColumns: {list(df.columns)}")
# print(f"\nMissing values:\n{df.isnull().sum()}")
# df.head()

In [15]:
#connect from local storage
df=pd.read_csv('/content/drive/MyDrive/heart_disease.csv')
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

## Section 3: Clean & Prepare

In [16]:
#remove the id that not important
df=df.drop('id',axis=1)
#rename output name
df=df.rename(columns={'num':'target'})
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,target
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [17]:
def binarization(x):
    if x != 0:
        return 1
    return 0
df['target']=df['target'].apply(binarization)
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,target
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       920 non-null    int64
 1   sex       920 non-null    object
 2   dataset   920 non-null    object
 3   cp        920 non-null    object
 4   trestbps  861 non-null    float64
 5   chol      890 non-null    float64
 6   fbs       830 non-null    object
 7   restecg   918 non-null    object
 8   thalch    865 non-null    float64
 9   exang     865 non-null    object
 10  oldpeak   858 non-null    float64
 11  slope     611 non-null    object
 12  ca        309 non-null    float64
 13  thal      434 non-null    object
 14  target    920 non-null    int64
dtypes: float64(5), int64(2), object(8)
memory usage: 107.9+ KB

In [19]:
#checking the null value of each column
df.isnull().sum()
#only column which have null value
df.isnull().sum()[df.isnull().sum()>0]

trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
dtype: int64

In [23]:
missing_pct = (df.isnull().sum() / len(df) * 100).round(1)
missing_pct[missing_pct>50]

ca      66.4
thal    52.8
dtype: float64

In [24]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.2)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.5.20)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 9.5 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 26.1 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 63.8 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 43.5 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 10.0 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.6 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

In [39]:
from ydata_profiling import ProfileReport
profile=ProfileReport(df,title='Heart Deaseas',explorative=True)

In [40]:
profile.to_file("cardiac_EDA.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/13 [00:00<?, ?it/s]
100%|██████████| 13/13 [00:00<00:00, 63.77it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [32]:
df = df.drop(missing_pct[missing_pct>50].index,axis=1)
#jar misssing vale 50% er kom tara bad

KeyError: "['ca', 'thal'] not found in axis"

In [33]:
df

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,target
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,1
916,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,0
917,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,1
918,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,0
919,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,1

In [38]:
num_col=df.select_dtypes(include=["number"]).columns
df[num_col]=df[num_col].fillna(df[num_col].median())
df[num_col]

     age  trestbps   chol  thalch  oldpeak  target
0     63     145.0  233.0   150.0      2.3       0
1     67     160.0  286.0   108.0      1.5       1
2     67     120.0  229.0   129.0      2.6       1
3     37     130.0  250.0   187.0      3.5       0
4     41     130.0  204.0   172.0      1.4       0
..   ...       ...    ...     ...      ...     ...
915   54     127.0  333.0   154.0      0.0       1
916   62     130.0  139.0   140.0      0.5       0
917   55     122.0  223.0   100.0      0.0       1
918   58     130.0  385.0   140.0      0.5       0
919   62     120.0  254.0    93.0      0.0       1

[920 rows x 6 columns]

In [41]:
df

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,target
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,1
916,62,Male,VA Long Beach,typical angina,130.0,139.0,False,st-t abnormality,140.0,NaN,0.5,NaN,0
917,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,1
918,58,Male,VA Long Beach,asymptomatic,130.0,385.0,True,lv hypertrophy,140.0,NaN,0.5,NaN,0
919,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,1

In [58]:
cat_col=df.select_dtypes(include=['object',"bool"]).columns
df[cat_col]=df[cat_col].fillna(df[cat_col].mode().iloc[0])
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,target
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,1
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0

## Feature Engineering

In [73]:
df_fe = df.copy()

# 1. Age Groups (clinical standard)
df_fe['age_group'] = pd.cut(df_fe['age'],
                            bins=[0, 40, 50, 60, 100],
                            labels=['<40', '40-50', '50-60', '60+'])

# 2. Blood Pressure Categories (AHA guidelines)
def bp_category(bp):
    if bp < 120: return 'Normal'
    elif bp < 130: return 'Elevated'
    elif bp < 140: return 'Stage1_HTN'
    else: return 'Stage2_HTN'

df_fe['bp_category'] = df_fe['trestbps'].apply(bp_category)

# 3. Cholesterol Risk Levels
def chol_risk(chol):
    if chol < 200: return 'Desirable'
    elif chol < 240: return 'Borderline'
    else: return 'High'

df_fe['chol_risk'] = df_fe['chol'].apply(chol_risk)

# 4. Heart Rate Reserve (thalach বদলে thalch ব্যবহার করা হয়েছে)
# Predicted max HR = 220 - age. Reserve = achieved / predicted
df_fe['predicted_max_hr'] = 220 - df_fe['age']
df_fe['hr_reserve'] = df_fe['thalch'] / df_fe['predicted_max_hr']

# 5. Heuristic Risk Score (sex == 'Male' এবং thalch ব্যবহার করা হয়েছে)
# Simple sum of known risk flags — doctors use similar heuristics
df_fe['heuristic_risk'] = (
    (df_fe['age'] > 55).astype(int) +
    (df_fe['sex'] == 'Male').astype(int) +
    (df_fe['chol'] > 240).astype(int) +
    (df_fe['trestbps'] > 140).astype(int) +
    (df_fe['exang'] == True).astype(int) +
    (df_fe['oldpeak'] > 2).astype(int) +
    (df_fe['thalch'] < 150).astype(int)
)

# 6. Interaction: Age × Cholesterol
# Atherosclerosis builds over time — age + cholesterol compound
# df_fe['age_chol_interaction'] = df_fe['age'] * df_fe['chol'] / 1000

# # 7. High ST Depression flag
# df_fe['high_oldpeak'] = (df_fe['oldpeak'] > 2.5).astype(int)

# print("✅ NEW FEATURES CREATED SUCCESSFULLY:")
# print(df_fe[['age_group', 'bp_category', 'chol_risk', 'hr_reserve',
#              'heuristic_risk', 'age_chol_interaction', 'high_oldpeak']].head())

# print(f"\n📊 Original features: 13")
# print(f"📊 Engineered features: 7")
# print(f"📊 Total now: {df_fe.shape[1]} columns")
df_fe.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,target,age_group,bp_category,chol_risk,predicted_max_hr,hr_reserve,heuristic_risk
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0,60+,Stage2_HTN,Borderline,157,0.955414,4
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,1,60+,Stage2_HTN,High,153,0.705882,6
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,1,60+,Elevated,Borderline,153,0.843137,5
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0,<40,Stage1_HTN,High,183,1.021858,3
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0,40-50,Stage1_HTN,Borderline,179,0.960894,0

In [77]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

# ১. কলামগুলোকে তাদের ধরন অনুযায়ী আলাদা করা
numeric_cols = ['age', 'trestbps', 'chol', 'thalch', 'oldpeak',
                'predicted_max_hr', 'hr_reserve', 'heuristic_risk']

nominal_cols = ['sex', 'dataset', 'cp', 'fbs', 'restecg', 'exang', 'slope']

ordinal_cols = ['age_group', 'bp_category', 'chol_risk']

# ২. অর্ডিনাল কলামগুলোর সঠিক ক্রম (Order) বলে দেওয়া
age_order = ['<40', '40-50', '50-60', '60+']
bp_order = ['Normal', 'Elevated', 'Stage1_HTN', 'Stage2_HTN']
chol_order = ['Desirable', 'Borderline', 'High']

# ৩. প্রত্যেকটি গ্রপ বা ধরনের জন্য আলাদা সাব-পাইপলাইন তৈরি করা

# নিউমেরিক পাইপলাইন: প্রথমে Median দিয়ে ইম্পিউট, তারপর স্ট্যান্ডার্ড স্কেলিং
numeric_transformer = Pipeline(steps=[
    # ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# নমিনাল পাইপলাইন: প্রথমে Mode দিয়ে ইম্পিউট, তারপর One-Hot Encoding
nominal_transformer = Pipeline(steps=[
    # ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False))
])

# অর্ডিনাল পাইপলাইন: প্রথমে Mode দিয়ে ইম্পিউট, তারপর নির্দিষ্ট ক্রম অনুযায়ী Ordinal Encoding
ordinal_transformer = Pipeline(steps=[
    # ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder(categories=[age_order, bp_order, chol_order],
                               handle_unknown='use_encoded_value', unknown_value=-1)),
    ('scaler', StandardScaler()) # অর্ডিনাল নাম্বারকেও (0,1,2) স্কেল করা ভালো
])

# ৪. ColumnTransformer দিয়ে সবগুলো পাইপলাইনকে একসাথে জোড়া লাগানো
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('nom', nominal_transformer, nominal_cols),
        ('ord', ordinal_transformer, ordinal_cols)
    ],
    remainder='passthrough' # বাকি ফিচারগুলো (যেমন binary flags বা target) যেভাবে আছে সেভাবেই থাকবে
)

# df_fe.head()
# ৫. ডেটা স্প্লিট করা (ফিট করার আগেই স্প্লিট করা ডেটা লিকেজ আটকানোর নিয়ম)
X = df_fe.drop(columns=['target'])
y = df_fe['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # 💻 পাইপলাইন রান করা (Train ডেটায় fit & transform হবে, টেস্ট ডেটায় শুধু transform হবে)
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# X_train_processed
# # কনভার্ট হওয়া কলামের নতুন নামগুলো বের করা (ভেরিফিকেশনের জন্য)
encoded_cols = preprocessor.get_feature_names_out()

# print("✅ Sklearn Imputation and Encoding Pipeline Completed Successfully!")
# print(f"Processed Train Shape: {X_train_processed.shape}")
# print(f"Total Features Generated: {len(encoded_cols)}")

In [79]:
# ১. NumPy array থেকে সুন্দর Pandas DataFrame তৈরি করা
X_train_df = pd.DataFrame(X_train_processed, columns=preprocessor.get_feature_names_out())
X_test_df = pd.DataFrame(X_test_processed, columns=preprocessor.get_feature_names_out())

# ২. ডেটাফ্রেমটি দেখতে কেমন হয়েছে তা চেক করা
X_train_df.head()

,num__age,num__trestbps,num__chol,num__thalch,num__oldpeak,num__predicted_max_hr,num__hr_reserve,num__heuristic_risk,nom__sex_Male,nom__dataset_Hungary,...,nom__cp_typical angina,nom__fbs_True,nom__restecg_normal,nom__restecg_st-t abnormality,nom__exang_True,nom__slope_flat,nom__slope_upsloping,ord__age_group,ord__bp_category,ord__chol_risk
0,0.902413,-0.083946,-0.262575,-0.694187,1.983624,-0.902413,-0.469687,1.386217,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.318666,0.240314,-1.253491
1,0.034776,0.987771,0.223659,-0.614999,-0.794406,-0.034776,-0.641663,0.030395,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.206938,1.142720,-0.061541
2,-0.290587,-0.083946,1.287871,0.097694,-0.331401,0.290587,0.012948,0.030395,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.206938,0.240314,1.130409
3,-0.399042,-0.619805,0.186962,0.810387,0.687210,0.399042,0.720417,-2.003337,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.904789,-0.662091,-0.061541
4,-0.182133,-0.619805,1.159431,1.364703,-0.609204,0.182133,1.381577,-0.647516,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.206938,-0.662091,1.130409

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, recall_score

# ১. মডেল দুটি ডিফাইন করা
log_reg = LogisticRegression(max_iter=1000, random_state=42)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# ২. Logistic Regression ট্রেইন এবং টেস্ট করা
log_reg.fit(X_train_processed, y_train)
y_pred_log = log_reg.predict(X_test_processed)

# ৩. Random Forest ট্রেইন এবং টেস্ট করা
rf_clf.fit(X_train_processed, y_train)
y_pred_rf = rf_clf.predict(X_test_processed)

# 📈 ফলাফল তুলনা করা
print("==================================================")
print(" 🩺 LOGISTIC REGRESSION PERFORMANCE")
print("==================================================")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log):.2f}")
print(f"Recall (Disease Detection): {recall_score(y_test, y_pred_log):.2f}")
print("\nDetailed Report:\n", classification_report(y_test, y_pred_log))

print("\n==================================================")
print(" 🌲 RANDOM FOREST PERFORMANCE")
print("==================================================")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.2f}")
print(f"Recall (Disease Detection): {recall_score(y_test, y_pred_rf):.2f}")
print("\nDetailed Report:\n", classification_report(y_test, y_pred_rf))

==================================================
 🩺 LOGISTIC REGRESSION PERFORMANCE
==================================================
Accuracy: 0.82
Recall (Disease Detection): 0.83

Detailed Report:
               precision    recall  f1-score   support

           0       0.77      0.80      0.78        75
           1       0.86      0.83      0.85       109

    accuracy                           0.82       184
   macro avg       0.81      0.82      0.82       184
weighted avg       0.82      0.82      0.82       184


==================================================
 🌲 RANDOM FOREST PERFORMANCE
==================================================
Accuracy: 0.83
Recall (Disease Detection): 0.82

Detailed Report:
               precision    recall  f1-score   support

           0       0.76      0.84      0.80        75
           1       0.88      0.82      0.85       109

    accuracy                           0.83       184
   macro avg       0.82      0.83      0.82       184
weighted avg       0.83      0.83      0.83       184

In [83]:
# ১. সেরা প্যারামিটার দিয়ে ফাইনাল মডেলটি তৈরি ও ট্রেইন করা
best_rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_leaf=4,
    min_samples_split=2,
    random_state=0
)
best_rf.fit(X_train_processed, y_train)

# ২. টেস্ট ডেটার ওপর ফাইনাল প্রেডিকশন করা
y_pred_best = best_rf.predict(X_test_processed)

# ৩. ফাইনাল পারফরম্যান্স রিপোর্ট প্রিন্ট করা
print("==================================================")
print(" 🔥 TUNED RANDOM FOREST FINAL PERFORMANCE")
print("==================================================")
print(f"Final Test Accuracy: {accuracy_score(y_test, y_pred_best):.2f}")
print(f"Final Test Recall (Disease Detection): {recall_score(y_test, y_pred_best):.2f}\n")
print(classification_report(y_test, y_pred_best))

# 📊 ফিচার ইম্পর্ট্যান্স বের করা (কোন ফিচার সবচেয়ে পাওয়ারফুল?)
importances = best_rf.feature_importances_
feature_imp_df = pd.DataFrame({
    'Feature': preprocessor.get_feature_names_out(),
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

print("\n👑 Top 5 Most Important Features in Your Model:")
print(feature_imp_df.head(5).to_string(index=False))

==================================================
 🔥 TUNED RANDOM FOREST FINAL PERFORMANCE
==================================================
Final Test Accuracy: 0.88
Final Test Recall (Disease Detection): 0.88

              precision    recall  f1-score   support

           0       0.83      0.87      0.85        75
           1       0.91      0.88      0.89       109

    accuracy                           0.88       184
   macro avg       0.87      0.87      0.87       184
weighted avg       0.88      0.88      0.88       184


👑 Top 5 Most Important Features in Your Model:
                Feature  Importance
    num__heuristic_risk    0.198846
        nom__exang_True    0.109932
           num__oldpeak    0.107369
nom__cp_atypical angina    0.083885
            num__thalch    0.073193

In [82]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, recall_score

# ১. একটি বিস্তৃত প্যারামিটার গ্রিড তৈরি করা (সব প্রধান প্যারামিটার কভার করা হয়েছে)
param_grid = {
    'n_estimators': [50, 100, 200, 300],          # গাছের সংখ্যা
    'max_depth': [None, 5, 10, 15, 20],           # গাছের সর্বোচ্চ গভীরতা
    'min_samples_split': [2, 5, 10],               # নোড স্প্লিট করার সর্বনিম্ন স্যাম্পল
    'min_samples_leaf': [1, 2, 4, 6],              # পাতার সর্বনিম্ন স্যাম্পল
    'bootstrap': [True, False]                     # বুটস্ট্র্যাপ স্যাম্পলিং পদ্ধতি
}

# ২. বেস মডেল ডিফাইন করা
rf_base = RandomForestClassifier(random_state=42)

# ৩. GridSearchCV সেটআপ করা (৫-কোল্ড ক্রস ভ্যালিডেশন সহ)
# n_jobs=-1 দিলে Colab-এর সব কোর একসাথে কাজ করবে, ফলে দ্রুত রান হবে
grid_search = GridSearchCV(
    estimator=rf_base,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

# ৪. গ্রিড সার্চ ট্রেইনিং শুরু করা
print("⏳ Grid Search রান হচ্ছে... (প্যারামিটারের কম্বিনেশন বেশি হওয়ায় ১-২ মিনিট সময় লাগতে পারে)")
grid_search.fit(X_train_processed, y_train)

# ৫. খুঁজে পাওয়া সেরা প্যারামিটার এবং স্কোর প্রিন্ট করা
print("\n👑 BEST PARAMETERS FOUND BY GRID SEARCH:")
print(grid_search.best_params_)
print(f"Best Cross-Validation Accuracy: {grid_search.best_score_:.4f}")

# ৬. স্বয়ংক্রিয়ভাবে তৈরি হওয়া সেরা মডেলটি দিয়ে টেস্ট ডেটা প্রেডিক্ট করা
best_grid_model = grid_search.best_estimator_
y_pred_grid = best_grid_model.predict(X_test_processed)

# 📈 ফাইনাল পারফরম্যান্স ইভ্যালুয়েশন
print("\n==================================================")
print(" 🚀 GRID SEARCH OPTIMIZED RANDOM FOREST PERFORMANCE")
print("==================================================")
print(f"Final Test Accuracy: {accuracy_score(y_test, y_pred_grid):.2f}")
print(f"Final Test Recall (Disease Detection): {recall_score(y_test, y_pred_grid):.2f}\n")
print(classification_report(y_test, y_pred_grid))

⏳ Grid Search রান হচ্ছে... (প্যারামিটারের কম্বিনেশন বেশি হওয়ায় ১-২ মিনিট সময় লাগতে পারে)
Fitting 5 folds for each of 480 candidates, totalling 2400 fits

👑 BEST PARAMETERS FOUND BY GRID SEARCH:
{'bootstrap': True, 'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 100}
Best Cross-Validation Accuracy: 0.8139

==================================================
 🚀 GRID SEARCH OPTIMIZED RANDOM FOREST PERFORMANCE
==================================================
Final Test Accuracy: 0.87
Final Test Recall (Disease Detection): 0.87

              precision    recall  f1-score   support

           0       0.82      0.87      0.84        75
           1       0.90      0.87      0.89       109

    accuracy                           0.87       184
   macro avg       0.86      0.87      0.87       184
weighted avg       0.87      0.87      0.87       184